### ISSUE TITLE
Lấy thông tin tài khoản thất bại: undefined

### ISSUE THREAD

**Issue by tuanteku9x** [zuydd/blum#1]
[ No 1 _ ID: 7255409818 _ IP: 🖥️ ] Lấy thông tin tài khoản thất bại: undefined
[ No 1 _ ID: 7255409818 _ IP: 🖥️ ] Checkin thất bại: undefined

**Comment by zuydd** [comment]
vẫn chạy ngon mà, kiểm tra lại mạng, data xem

**Comment by tuanteku9x** [comment]
> vẫn chạy ngon mà, kiểm tra lại mạng, data xem

ý mình nhầm, con major :))

**Comment by zuydd** [comment]
lần sau bạn nhớ báo lỗi đúng project nhé, báo kiểu này khổ mình
